# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    tags:
      - "v*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: |
        dotnet build --configuration Release --no-restore
        dotnet publish -c Release -r win-x64
        zip -r gif2webp.zip .\bin\Release\net8.0-windows\win-x64\publish\*
        
    - name: Create release 
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
          gh release create "gif2webp.zip"       
